Jenkinsfile.groovy, package.json
Actually tags github repo with `package.json` version
=> adds git tag to QA deploy stage

config.js, services/clinical/index.js
Clinical service root should not include the /submission path. Services were updated to reflect this.
A devops task is required to update the injected env value for dev and qa servers.
=> :bug: Update paths for clinical services

app.js, config.js, package-lock.json, package.json, resources/swagger.yaml, routes/clinical.js, utils/grpcUtils.js
Added swagger docs for the /clinical/template:schema endpoint.
=> Enhancement: Added swagger docs

schemas/Program/index.js
Create Program simply returns true/false for result, no program data returned.
=> No Fetch after Create Program

schemas/User/index.js
=> Fix Access Key fetch when user has no keys

package.json, schemas/User/index.js
- Prevent error in getAccessKeys when user has no keys
=> Release Candidate 1.2.1

package-lock.json, package.json, schemas/Clinical/index.js
Registration records no longer have hardcoded field names, they use the exact names and fields as returned form Clinical Service.
Example registration upload request for the new fields structure:
```
mutation($registration:Upload!) {
uploadClinicalRegistration(shortName:"Z125-AU", registrationFile:$registration) {
id
records {
row
fields {
name
value
}
}
}
```
Example response:
```
{
"data": {
"uploadClinicalRegistration": {
"id": "5d812fd9d362dac6721d4acb",
"records": [
{
"row": 0,
"fields": [
{
"name": "program_id",
"value": "Z125-AU"
},
{
"name": "submitter_donor_id",
"value": "abcd-123"
},
{
"name": "gender",
"value": "Male"
},
{
"name": "submitter_specimen_id",
"value": "ss123-adsasd-dads"
},
{
"name": "specimen_type",
"value": "FFPE"
},
{
"name": …
```
=> Implement Generic Field structure for registration records

routes/clinical.js
=> Support tsv file

schemas/Clinical/index.js, services/clinical/index.js
added validate endpoint for clinical validate
=> validate endpoint

schemas/Clinical/index.js
add createdAt and fileName to clinical response 
=> add fileName and createdAt to Clinical resp + prettier

app.js, package-lock.json, package.json, services/ego/index.js, utils/grpcUtils.js, utils/logger.js
- adds `winston` for logging
Helps for getting timestamp in logs so we can hunt down the performance bottleneck
=> 🔊 uses winston to improve logging

app.js
logs graphql query and variables for every gql request
=> 🔊 adds graphql request logging query and variables

schemas/Clinical/index.js
update clinical entity to match with added field in clinical - for this PR: https://github.com/icgc-argo/argo-clinical/pull/156
also added fileErrros filed - for this PR: https://github.com/icgc-argo/argo-clinical/pull/157
=> update clinical entity

schemas/Clinical/index.js, services/clinical/index.js
New mutations for Commit and Approve of clinical active submissions and the connecting services
=> Clinical commit and approve submission

schemas/Clinical/index.js
a lot of changes :P
No this is just adding a placeholder
=> added createdAt

routes/clinical.js, schemas/Clinical/index.js, services/clinical/index.js
- added a query to ask clinical for clinical types list
- also take actual createdAt from clinical entity
- also also allow null values in clinical records
- changed shortName to programShortName for clinical submissions
Note: merge after https://github.com/icgc-argo/argo-clinical/pull/173
=> add query for clinical type & createdAt

schemas/Clinical/index.js
includes schemaErrors as a field in clinical entity
=> includes schemaErrors as a field in clinical entity

schemas/Clinical/index.js
Just adding some comments to help navigating user navigate the schema more smoothly
=> 📝 adds some explanatory comments to clinical schema

schemas/Clinical/index.js
You know what's up :P
We decided to move forward with this, using the solution from gateway
=> ✨ includes empty clinical entities in the ClinicalSubmissionData type

schemas/Clinical/index.js, services/clinical/index.js
New mutation, clear a file or all files from clinical submission.
=> ✨ Add Clear Clinical Submisison mutation

resources/swagger.yaml, routes/clinical.js, schemas/Clinical/index.js, services/clinical/index.js
- added support for reopen
- also removed .zip from all template endpoint/path
=> Add Reopen Clinical Submission Mutation

schemas/Clinical/index.js
adding two fields that clinical returns and UI needs for signoff
=> added updatedAt and updatedBy fields

schemas/Program/index.js
- needed for https://github.com/icgc-argo/platform-ui/pull/783
- updates `createProgram` mutation to return the program created
=> 💥 make createProgram mutation return new program created

schemas/Clinical/index.js, services/clinical/index.js
no change on gql schema
related to clinical PR
https://github.com/icgc-argo/argo-clinical/pull/215
=> refactor to accept the new registration stat structure

schemas/Clinical/index.js
clinical returns batchNames so update gateway to convert to fileNames
ref PR: https://github.com/icgc-argo/argo-clinical/pull/221
=> updated FileError to match clinical BatchError

schemas/Clinical/index.js
- There was a naming bug in clinical, should be batchErrors
will open and merge after https://github.com/icgc-argo/argo-clinical/pull/227
=> missed a rename, and refactor

schemas/Clinical/index.js
- clean up the clinical schema (removed a lot of repetitive code)
- msg -> message (for consistency)
Note: connected to PR https://github.com/icgc-argo/argo-clinical/pull/250
=> clinical schema update and cleanup

schemas/Clinical/index.js
looks like registration query was returning a empty registration, fixed it :+1: 
=> fix registration query

package-lock.json, schemas/Clinical/index.js
=> read schema errors from clincial entity

schemas/Clinical/index.js, utils/restUtils.js
- added generic handle 5xx errors
- throw ApoolloError (ServerError wasn't defined)
- some cleanup
this is to handle new error from clinical [(PR#266)](https://github.com/icgc-argo/argo-clinical/pull/266) and possibly else where
=> Add 5xx error handling

schemas/Clinical/index.js, services/clinical/index.js
- added new query for UI to get schema version
- also added invalid_by_migration to code list
=> added get clinical schema version

schemas/Clinical/index.js, services/clinical/index.js
connected prs: 
https://github.com/icgc-argo/argo-clinical/pull/344
https://github.com/icgc-argo/platform-ui/pull/994
=> add new query to get submission state

schemas/Clinical/index.js
your party parrot distracted me and I missed this...
=> fix funciton name

schemas/User/index.js, services/ego/index.js
API key generation involves deleting existing keys. Since the first time a user generates an api key, there will be nothing to delete so the deletion fails
=> 🐛 fixes api token generation for the first time

schemas/User/index.js, services/ego/index.js
needs to update to compute expiry from `expirtyDate` and `issueDate`
=> :bug: fix ego api key expiry

src/config.ts, src/schemas/User/index.js
Setup to get daco access from scopes
=> 🐛 Get daco from scopes

src/schemas/Program/index.js
Changes to consume new daco_approved boolean value from program service
changes to accomo
=> add daco approved to user details

package-lock.json, package.json
=> update proto version

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/types.ts
The mockups have process status as `COMPLETE` not `COMPLETED`. I;m changing this so its easier to deal with in the UI.
See mockup example:  https://projects.invisionapp.com/share/FES2W305M6Q#/screens/392892045
=> change COMPLETED to COMPLETE for UI

src/app.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts
- handles ES read errors
- removes the `PROGRAM_DASHBOARD_SUMMARY_ENABLED` feature flag
=> ✨ handles elasticsearch read errors

src/app.ts, src/schemas/ProgramDonorSummary/resolvers/index.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
- forgot to actually call the resolvers :P
- also the root logger is annoying...
=> 🐛 fixes dashboard resolvers

src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts
=> use raw/publised sample fields

src/routes/clinical-proxy.ts
had to set `changeOrigin` so the proxy can resolve the clinical name-based site
=> set changeOrigin true

src/schemas/Helpdesk/gqlTypeDefs.ts
seems like schemas need a query root to work
=> Add dummy query root to jira schema

src/schemas/Clinical/index.ts
=> join array with delimiter char for clinical array value

package-lock.json, package.json
related release: https://github.com/icgc-argo/argo-clinical/pull/539
=> update to 1.14.0

src/app.ts
use `Promise.all` to parallelize schema initializations
=> ⚡️ parallelize initialization process to boost startup time

compose/file_centric/file_mapping.json, src/resources/arranger_es_metadata.json, src/routes/file-centric-tsv/types.ts
=>  💥 updates index mapping

src/routes/file-centric-tsv/index.ts, src/routes/file-centric-tsv/utils.test.ts, src/routes/file-centric-tsv/utils.ts
- adds a test
- renames function and input type for easier test mocking
- fixes the bug, it was missing the `\n` after every chunk of data.
=> 🐛 fixes tsv generration in writeTsvStreamToWritableTarget

src/config.ts, src/routes/clinical-proxy.ts, src/services/clinical/index.js
=> update deprecated cliical endpoints

compose/donors.json, src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
- adds aggregation for donors' data dictionary valid status
=> :sparkles: adds aggregation for donor valid status

src/app.ts, src/utils/ArgoApolloServer.ts
- refactoring the custom Apollo server implementation to be a class extension
=> Refactors the ApolloServer implementation

src/routes/file-centric-tsv/tsvSchemas/scoreManifest.ts
changed header name in tsv file
=> change project_id to program_id

src/schemas/Helpdesk/gqlTypeDefs.ts
=> delete deprecated mutation for making jira ticket

.gitignore, .schema.env, package-lock.json, src/config.ts, src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts, src/schemas/Helpdesk/index.ts, src/services/reCaptcha/index.ts
add datawarnings to clinical entity data
use stub recaptcha client if flag disabled
=> add datawarnings to clinical entity data

package-lock.json, package.json, src/app.ts, src/utils/logger.ts
Adds HTTP log to help with debugging.
=> :sparkles: adds http logger

package-lock.json, package.json
Updates to the newest version of arranger to support https://github.com/overture-stack/arranger/issues/615
=> updates Arranger

compose/common.ts, compose/generateFake.ts, compose/releaseStageEsInit.ts, package.json
- change npm script name just for consistency
- updates indexing function to use bulk index
- adds support for password-protected ES
- sets fake data generation target to `compose/file_centric/sample_file_centric.json`
=> ⚡️ improves script performance

src/routes/file-storage-api/handlers/downloadHandler.ts
resolves file object id to repository url
=> :sparkles: resolves repository url from file object id

compose/common.ts, compose/generateFake.ts, compose/releaseStageEsInit.ts
- adds new env for script
- changes fake data repository url
=> :sparkles: allows specifying script ES host through env

src/resources/swagger/file-storage-api.yaml
- removes unused endpoint
- adds query doc for `/download`
=> :memo: updates swagger doc

compose/common.ts, compose/generateFake.ts, compose/releaseStageEsInit.ts, package-lock.json, package.json, tsconfig.script.json
=> Feat/mock file data with UUID

src/app.ts
=> :bug: fixes context extraction

.gitignore, .schema.env, package-lock.json, package.json, src/app.ts, src/schemas/Banner/banner-ti.ts, src/schemas/Banner/index.ts, src/schemas/SystemAlert/index.ts, src/schemas/SystemAlert/systemAlert-ti.ts
Some file changes appear to have been made in an RC branch. Merging everything back into dev to get it caught up.
=> Merge Back to Dev - Master @3.13.2

package-lock.json, package.json, src/routes/file-storage-api/handlers/test/utils.ts, src/schemas/Arranger/test/utils.ts, src/schemas/User/index.ts, src/services/ego/index.ts
Updates req params for scopes, apiKey requests due to Ego 4 [api changes](https://wiki.oicr.on.ca/display/OV/User+Creation+Test+Scenarios#UserCreationTestScenarios-Breakingchanges:)
Ran `npm audit fix` due to >4000 issues, looks related to lodash version
=> 👽 Ego 4 api updates

package-lock.json, package.json, src/routes/file-centric-tsv/index.ts
This PR fixes security vulnerabilities. 
=> Release Candidate 3.18.0

README.md
Update README to document adding new fields to graphql schema programDonorSummaryEntries. 
=> document adding new fields to graphql schema programDonorSummaryEntries

package.json
Tagging conflict on 3.18.0
This includes all changes from: https://github.com/icgc-argo/platform-api/pull/420
=> Release 3.18.1

src/app.ts, src/resources/swagger/index.yaml, src/routes/file-centric-tsv/index.ts, src/routes/file-centric-tsv/utils.test.ts, src/routes/file-centric-tsv/utils.ts
Adds JWT based Auth Filters to TSV download endpoints, controlled by META_ACCESS_FILTER flag in env props.
=> Access Filter for TSV downloads

package.json, src/app.ts
- Correct CORS config to specify headers exposed instead of headers allowed.
=> Release Candidate 3.20.2

package.json, src/schemas/Arranger/getAccessControlFilter.ts, src/utils/commonTypes/EsFileCentricDocument.ts
- Access filters correctly apply filters to meta properties.
=> Release Candidate 3.20.4

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
Add filter option to filter donor entries by alignment workflow status. 
=> feature to filter donors by alignment status

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
- adds sanger VC status filter to donor dashboard API
- adds mutect 2 status filter to donor dashboard API
=> add sanger and mutect status filter

src/resources/arranger_es_metadata.json
Adds 'File ID' to file centric extended mapping
=> Add File ID to Extended Mapping

package-lock.json, src/routes/file-centric-tsv/tsvSchemas/scoreManifest.ts
Updates scoreManifest to include File ID
Connects to https://github.com/icgc-argo/platform-ui/pull/2157/
=> ✨ Feat #2019 Add File ID to scoreManifest

src/routes/file-centric-tsv/index.ts
* Append timestamp (HHmmss) to File Manifest download filename
=> ✨ Add Timestamp to File Manifest Filename (#2147)

package-lock.json, package.json
Fixes merge conflicts between `master` and `develop`
=> 🐛 Fix Conflicts with 3.28.0 Merge-back

src/routes/file-centric-tsv/tsvSchemas/scoreManifest.ts
Removes File ID from manifest to address score/song conflicts
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-ui/2192
=> Remove File Id from Manifest Fields

package-lock.json, package.json, src/routes/file-centric-tsv/tsvSchemas/scoreManifest.ts
* Remove File Id from Manifest Fields ([#2192](https://github.com/icgc-argo/platform-ui/issues/2192))
=> 🔖 Release 3.28.2

compose/file_centric/file_mapping.json
=> 🐛 Remove nesting from `metrics` mapping

package-lock.json, package.json, src/routes/file-centric-tsv/tsvSchemas/scoreManifest.ts
* Update file-centric mapping to include `metrics`
=> 🔖 Version 3.29.0 

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
Adding 3 RNA column filters: rna registered samples, rna raw reads, rna alignment status.
=> RNA table filters

src/routes/clinical-proxy.ts, src/schemas/Clinical/gqlTypeDefs.ts
Restores Clinical TSV Download Endpoint
=> Hotfix: Restore Clinical Download Endpoint

src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts
* Updates ClinicalError response to return errors for different entities
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-api/542
=> ❗ #542 Submitted Data Error summary

package-lock.json, package.json
=> minor dep upgrades

src/schemas/ProgramDonorPublishedAnalysisByDateRange/gqlTypeDefs.ts, src/schemas/ProgramDonorPublishedAnalysisByDateRange/resolvers/types.ts
=> update programDonorPublishedAnalysisByDateRange api to include RNA data

package-lock.json, package.json
For RNA- Seq epic. 
Adds two fields to `programDonorPublishedAnalysisByDateRange` API: https://github.com/icgc-argo/platform-api/pull/580
=> Release Candidate 3.34.0

src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts
Moves Clinical Errors from nested resolver into Clinical Entity query, which allows sorting on API instead of on FE
Changes completionStats type to Float (source of bug)
Relates to: https://github.com/icgc-argo/platform-ui/pull/2358
=> ↕️ Feat/2265 Entity Data table sort

src/routes/clinical-proxy.ts, src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts, src/services/clinical/index.js
=> 🔎 #2269 Search Clinical Data by Donor

src/schemas/Clinical/index.ts
Handles Empty SearchResult response
=> #2387 Submitted Data URL Params

src/resources/swagger/index.yaml, src/routes/clinical-proxy.ts
* Adds router endpoint for submitted clinical data TSV downloads
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/icgc-argo/platform-api/544
Relates to:
UI: https://github.com/icgc-argo/platform-ui/pull/2404
Service: https://github.com/icgc-argo/argo-clinical/pull/819
=> 💿 #544 Clinical Data TSV downloads

package-lock.json, package.json, src/resources/swagger/index.yaml, src/routes/clinical-proxy.ts, src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts
* Clinical Data TSV Downloads
https://github.com/icgc-argo/platform-api/issues/544
* Default Search Result Value
https://github.com/icgc-argo/platform-api/pull/604
* Core Completion % as Float
https://github.com/icgc-argo/platform-api/pull/603
=> 🚀 Rc 3.36.0

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
- add filters and aggregations for tumor normal data
- add filters and aggregations for tumor normal matched pairs
=> #610: add DNA filters

src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
Adds ElasticSearch handler for Valid/Invalid Donor filters
Relates to: https://github.com/icgc-argo/platform-ui/pull/2420
=> #2315 Program Dashboard Valid / Invalid Donor Filter

src/config.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts
- increase graphql max cost
- fix aggregations for matched pair filters
=> #610: DNA filters - fix bugs

package-lock.json, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts
- update donor/search filters to match count filters for DNA raw reads
- update "no matched pairs" to remove "at least one T or N" condition
=> #626 - fix DNA filters

.eslintrc.js, Dockerfile, Jenkinsfile.groovy, README.md, package-lock.json, package.json, src/routes/file-centric-tsv/utils.test.ts, src/schemas/Program/index.js, src/utils/logger.ts, tsconfig.json
Adds a few goodies to facilitate implementation and troubleshooting.
These were useful trying to figure out a cryptic set of errors when a feature was deployed without its corresponding environment variables. It also covers a few bugs found along the way (mostly TS migration tasks).
=> fix Program Service not reachable as a docker container

src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts
Removes FamilyHistory from CoreCompletion type
Related UI PR:
https://github.com/icgc-argo/platform-ui/pull/2612
=> Remove Core Complete Family History

package-lock.json, package.json
Patches critical security vulnerabilities
Relates to: https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-api/567
=> 🐛 Run Npm Audit Fix w/ legacy-peer-deps

src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts, src/services/clinical/index.js
Changes related to Clinical #1006: https://github.com/icgc-argo/argo-clinical/pull/1051
ClinicalErrors will always at least return an array
=> #1006 Prevent null clinicalErrors

src/schemas/Helpdesk/jiraRequests.ts, src/utils/restUtils.ts
=> 🐞  TS Util Issues

package-lock.json, package.json, src/routes/clinical/clinical-api.ts, src/schemas/Helpdesk/jiraRequests.ts, src/utils/restUtils.ts
- Download clinical data for files
=> Release Candidate 3.42.0

package-lock.json, package.json
Use latest Arranger version
Related to investigation for: 
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/roadmap/1057
=> Use Arranger 2.19.4

package-lock.json, package.json, src/resources/swagger/index.yaml, src/routes/clinical/arranger.ts, src/routes/clinical/clinical-api.ts
- https://github.com/icgc-argo/platform-api/pull/721
=> Release Candidate 3.45.0
