icgc-argo/platform-api

utils/grpcUtils.js
- logs out the full error when retrying grpc method
=> 🔊 logs out the full error when retrying

services/programService/index.js
adds a config found at: https://cs.mcgill.ca/~mxia3/2019/02/23/Using-gRPC-in-Production/
=> 🐛 introduces grpc configs to bump up keep alive signal

schemas/Clinical/index.js
- includes schema errors in ClinicalSubmissionData
- creates `ClinicalEntityError` gql interface that is implemented by `ClinicalSubmissionError`
and `ClinicalSubmissionSchemaError`. `ClinicalSubmissionSchemaError` needs to have a `clinicalType` attached
=> includes schema errors in ClinicalSubmissionData

schemas/Clinical/index.js
two problems:
1) was looking in wrong place for `clinicalEntities`
2) did not include `clinicalType` in the clinicalEntity when it is not empty
=> 🐛 fixes the wrong place to look for clinicalEntities

schemas/Clinical/index.js
turns out for schema errors, `value` can be null
=> 🐛 ClinicalSubmissionSchemaError value field can be null

.vscode/settings.json, package-lock.json, package.json, schemas/User/index.js, services/ego/index.js
- updates ego according to these changes here: https://github.com/overture-stack/ego/pull/420
- adds some [JSDoc](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc) to provide type info (I think we should do more of this in the gateway, it's not perfect but better than nothing if we're not getting the luxury of TypeScript)
=> updates Ego api to match with latest release

schemas/Clinical/index.js
`null` was being returned by GQL for `value`, but it was reporting other fields as being null.
=> fix null value not being checked correctly

src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts
Since clincial can take array inputs in file, it can also now return array values.
This PR is to address that so that all `value` fields are converted to string
=> make sure any `value` fields from clinical is string

package-lock.json, package.json, src/app.ts, src/routes/donor-aggregator-api.ts, src/routes/file-storage-api/handlers/downloadHandler.ts, src/routes/file-storage-api/handlers/entitiesHandler.ts, src/routes/file-storage-api/handlers/entitiesIdHandler.ts, src/routes/kafka-rest-proxy.ts, src/routes/middleware/authenticatedRequestMiddleware.ts, src/routes/utils/accessValidations.ts
The `/kafka/:topic` resolver is used for external applications to send messages to the DCC kafka. This PR adds permission checks to the endpoint that will require a scope which contains the topic in the policy name. The pattern checking for this scope is handled by the common validation library [icgc-argo/ego-token-utils](https://github.com/icgc-argo/ego-token-utils), with the new rules added in version [8.1.0: canWriteKafkaTopic](https://github.com/icgc-argo/ego-token-utils/pull/59) .
To achieve this, the AuthendticatedRequestMiddleware was extended to return the `serializedScopes` object (scopes as an array of strings instead of scope objects). This auth middleware was added to the kafka router and used with the validations in ego-token-utils.
Changes to the …
=> Add Topic Permission checking to Kafka endpoint

compose/sample_schema.json, src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
This PR implements the feature to filter donor summary entries by partially matching donor id and submitter donor id. 
Examples: 
when querying data with the following query, if filter value is `donor`, query should return all results that contains `donor` as either donor id or submitter id. 
```
query{
programDonorSummaryEntries (
programShortName: "ROSI-RU",
sorts:{
field:donorId, order: asc
},
filters: [
{ 
field: combinedDonorId,
values: ["donor"]
}
]
) {
id
donorId
submitterDonorId
programShortName
submittedCoreDataPercent
registeredNormalSamples
registeredTumourSamples
alignmentsCompleted
alignmentsRunning
alignmentsFailed
sangerVcsCompleted
sangerVcsRunning
sangerVcsFailed
mutectFailed
mutectRunning
mutectCompleted
processingStatus
updatedAt
createdAt
}
} …
```
=> feature to filter donor dashboard entries by donor id and submitter donor id

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts
Fix donor id filter only accepting 1 value by implementing bool should queries to allow donor id filter accept an array of values. 
=> donor id filters accept array of values

src/utils/commonTypes/EsFileCentricDocument.ts
Facet aggregations were wrong because the access filters and the user selected filters were using the same properties. The constants needed their paths correctly written to indicate the meta fields. Easy constants changed to get the generated access filters working as expected.
=> Correct path to access filter properties

src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
Adds a new filter field `registeredSamplePairs` to enum `ProgramDonorSummaryEntryField` for filtering donors by valid/invalid sample pairs. 
=> add sample pair filter

compose/docker-compose.yml, package-lock.json, src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/SummaryStats.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
Feature to add aggregation fields  to `programDonorSummary` and `programDonorSummaryStats` API, new fields added are:
```
coreCompletion {
completed
incomplete
noData
}      
sampleStatus {
valid
invalid
}
rawReadsStatus {
valid
invalid
}      
alignmentStatusCount{
completed
inProgress
failed
noData
}
sangerStatusCount{
completed
inProgress
failed
noData
}
mutectStatusCount{
completed
inProgress
failed
noData
}
```
=> add list aggregation to programDonorSummary - stats API

src/routes/file-storage-api/handlers/entitiesHandler.ts, src/routes/file-storage-api/utils.ts, src/utils/commonTypes/EsFileCentricDocument.ts
The Index Files associated with a file are included in the documents in the file_centric index. This PR takes advantage of this to include those files in the `/entries` requests from the score client. The end result is that a request for a file download will now also send the index file to the score client for download
=> Add index files to score downloads

package.json, src/routes/file-storage-api/handlers/downloadHandler.ts, src/routes/file-storage-api/handlers/entitiesHandler.ts, src/routes/file-storage-api/handlers/entitiesIdHandler.ts, src/routes/file-storage-api/handlers/test/entitiesId.test.ts
Error message phrasing updates, and sending messages for all known error cases on file download.  These include the no file found, access token invalid, and missing permissions cases.
=> Error messages for entity download error cases

src/resources/swagger/index.yaml, src/routes/clinical-proxy.ts
Adds a new resolver for `/template/all/` endpoint to allow optional downloading for sample registration file.
=> add option to exclude sample registration downloading

src/routes/file-storage-api/handlers/entitiesIdHandler.ts
Removed Authenticated check at start of entitiesId request handler and this allows completion through the whole process, all required auth rules still respected.
=> Allow Open+Public files to be downloaded without auth

compose/donors.json, compose/sample_schema.json, src/schemas/ProgramDonorPublishedAnalysisByDateRange/gqlTypeDefs.ts, src/schemas/ProgramDonorPublishedAnalysisByDateRange/resolvers/types.ts, src/schemas/ProgramDonorSummary/gqlTypeDefs.ts, src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts, src/schemas/ProgramDonorSummary/resolvers/types.ts
* Exposes new fields related to Open Access workflows: `openAccessCompleted`, `openAccessRunning`, `openAccessFailed`, and `openAccessFirstPublishedDate`
* Also adds filters for donors by Open Access workflow status
=> 👽️ Add Open Access Fields to Donor Summary Schema (#490)

compose/file_centric/file_mapping.json
Adds `metrics` object to the mapping for the file-centric index. From: https://github.com/icgc-argo/files-service/pull/104
=> 🔧 Update File Centric ES Mapping to Include `metrics` Object

src/config.ts, src/resources/swagger/file-storage-api.yaml, src/routes/file-storage-api/handlers/downloadHandler.ts, src/routes/file-storage-api/index.ts
Download files from object storage and pipe them to the client with the expected filename, instead of forwarding the download URL. Changes `/storage-api/get-download-url` endpoint to `/storage-api/download-file`, and sets the download file size limit to 5MB.
**Commits:**
🔧 Set Default Limit For Small File Downloads to 5MB 
💥 Change Small File Download Logic
* Download files from object storage and pipe them to the client instead of forwarding the download URL
* Set the filename for the piped file using the `content-disposition` header
=> 💥 Change Small File Download Logic (#500)

src/routes/kafka-rest-proxy.ts
Sets the json payload size to 1Mb for the kafka proxy endpoint. This is the max message size accepted by kafka. Song is sending messages that are larger than the default body-parser 100kb limit.
=> Kafka Proxy Payload Size set to 1Mb

src/schemas/ProgramDonorSummary/resolvers/summaryEntriesAndStats.ts
Wrap the DNA raw reads (no matched pairs & some data submitted) filter in a `must()` condition.
=> #610: fix DNA raw reads filter

compose/docker-compose.yml, src/config.ts, src/schemas/Program/index.js, src/services/programService/grpcClient.js, src/services/programService/httpClient.js, src/services/programService/index.js, src/utils/restUtils.js
Connecting to Program Service's HTTP endpoints by creating a new resolver and error handler. The HTTP endpoints are public. The original endpoints (GRPC) needs authentication. The system will check whether the query contains info that are all public. If that's the case, automatically, the HTTP endpoints is used. And this could be done without auth.
Vice versa, if a query contain private info, then GRPC endpoints are used and this would require auth. 
=> Accessing Program Service HTTP Public Endpoint 

compose/docker-compose.yml, package-lock.json, src/resources/swagger/index.yaml, src/routes/clinical-proxy.ts, src/services/clinical/index.js, src/services/clinical/utils.ts
Updates Clinical API based on breaking changes here: https://github.com/icgc-argo/argo-clinical/pull/980
The clinical data/error/search APIs all use POST method now, with several query params moved into the request body.
This also makes the filter pagination properties useful in gql, adding them to the request to clinical.
This has been tested vs the clinical API locally but not in context in the UI. That will require some further trials after dev deploy.
=> Update Clinical Data/Error/Search to use POST

src/constants/http.ts, src/schemas/Clinical/gqlTypeDefs.ts, src/schemas/Clinical/index.ts, src/services/clinical/index.js
GQL Resolver for ClinicalError needed to be defined in two places, once for direct query from root and then again from nested in clinicalData. This was found because the getClinicalError api funciton was broken in the previous PR, so this was fixed in a way to satisfy both.
In addition, it was found that the clinical API was not parsing the JSON bodies without the `Content-Type` header set to `application/json` so that was added to the POST requests.
=> Fix clinicalError resolver, both nested in clinicalData and at root

src/schemas/Program/index.js
This change acommodates a change to the response structure of programs from Program Service.
The ProgramService is removing `processingRegions` as a program property. The http response formatting code in our program resolver assumed the presence of some fields without checking for them. Updating this code block with optional chaining and default values resolves the breaking issue.
=> Program Resolver format HTTP response bug from missing properties

src/resources/arranger_es_metadata.json
Adding `has_clinical_data` property to the arranger extended and aggs_state metadata.
=> Add `has_clinical_data` to arranger metadata

src/services/programService/httpClient.js, src/utils/restUtils.ts
Simplify error handling to make more consistent throughout.
Correct a bug introduced by restUtils refactoring that caused a duplicate read of response body.
=> Prevent double response body read from error handler

src/app.ts, src/resources/arranger_es_metadata.json, src/resources/swagger/index.yaml, src/routes/clinical/clinical-api.ts
- Cleanup text in Arranger mapping for `has_clinical_data` field
- Switch to `object_id` to identify files for the download clinical data by file endpoint
- Small change greatly simplifies changes required on UI
=> Download Clinical Data by File API Updates

src/schemas/Program/index.js, src/services/programService/httpClient.js, src/services/programService/index.js
Refer to ticket #691 
Plateform API is able to make a gql query to dataCenters. Use this query for testing:
`{
dataCenters {
name
shortName
id
organization
email
uiUrl
gatewayUrl
analysisSongCode
analysisSongUrl
analysisScoreUrl
submissionSongCode
submissionSongUrl
submissionScoreUrl
}
}`
jwt token is needed for this query.
**Ticket Checklist**
=> #691/ Adding data center gql type, query and resolver

src/config.ts
Removed type assertions reading process.env variables.
For the variables that are required to have a value (`undefined` is breaking) I have given the config value a default string that will be invalid in that context, the default value will declare the env variable is missing. This should help troubleshooting cases where this env value is missing!
=> Replace config type assertions with defaults declaring missing variable

src/schemas/Program/index.js, src/services/programService/httpClient.js
Add an optional parameter (shortName) to the dataCenter query, where resolver will filter out the dataCenter data with the shortName.
**Ticket Check List**
**Testing Query**
use the following query to test result. 
Note: There are two dataCenter objects now with the shrotName, DC1 and DC2. 
`{
dataCenters(shortName: "DC1") {
id
shortName
name
organization
email
uiUrl
gatewayUrl
analysisSongCode
analysisSongUrl
analysisScoreUrl
submissionSongCode
submissionSongUrl
submissionScoreUrl
}
}`
=> #692 Add data center name filter to dataCenter gql query

src/schemas/Program/index.js, src/services/programService/httpClient.js
Add dataCenter property to gql Program type. Update private field list, making query with dataCenter field a private Program route.
**Testing Query**
Now GET program and listPrograms can fetch dataCenter info.
1. for GET program:
```
{
program(shortName: "ALEXIS-CA") {
dataCenter {
id
shortName
name
uiUrl
gatewayUrl
}
}
}
```
2. listPrograms
```
{
programs {
dataCenter {
id
shortName
name
uiUrl
gatewayUrl
}
}
}
```
=> Add `dataCenter` to GQL `Program` type

src/schemas/Program/gqlTypeDefs.js, src/schemas/Program/index.js, src/services/programService/index.js
Removes 'regions' from gql resolvers + types
https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/platform-api/690
https://github.com/icgc-argo/platform-ui/pull/2753
=> 🌍 Remove Regions from Types + Resolvers

src/schemas/Program/gqlTypeDefs.js, src/schemas/Program/index.js, src/services/programService/index.js
Update TypeDefs & resolvers to allow DataCenter fields
Related UI Changes: https://github.com/icgc-argo/platform-ui/pull/2754
Issues: https://github.com/icgc-argo/platform-api/issues/693
https://github.com/icgc-argo/roadmap/issues/1098
=> 💾  #1098 Add Program Data Center fields

src/resources/swagger/index.yaml, src/routes/clinical/arranger.ts, src/routes/clinical/clinical-api.ts
**Link to Issue**
- icgc-argo/roadmap#1056
- adds support for "download all files" from file repo
- uses Arranger for inbuilt permission management
- queries arranger GQL endpoint on self, can't target Arranger api directly as it's not exported from module (using old version of Arranger)
- performant even with 12k files selected, looks like we have internal Arranger code already handling large selections https://github.com/overture-stack/arranger/blob/legacy/modules/mapping-utils/src/resolveHits.js#L38
=> Endpoint to download clinical data for a filtered query
